name: reorg

services:

  # PostgreSQL metadata storage
  db:
    image: postgres:17
    container_name: db
    ports:
      - 5432:5432
    volumes: 
      - ./internal/db/pg-data:/var/lib/postgresql/data
      - ./internal/db/db-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  # MinIO object storage
  obj-store:
    image: quay.io/minio/minio:latest
    # Add start-up script to config minio using mc?
    container_name: obj-store
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./internal/obj-store/minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"

  # PGAdmin
  pgadmin: 
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 1234:80
    volumes:
      - ./internal/pgadmin/pgadmin-data:/var/lib/pgadmin
    depends_on: 
      - db

  # Application
  # reorg-app:
    # image: [should the dockerfile be on a registry or on disk?]
    # container_name: reorg-app

